# Generated by Django 5.2.5 on 2025-08-22 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("gym", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="user",
            field=models.ForeignKey(
                limit_choices_to={"role": "client"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="workoutsession",
            name="clients",
            field=models.ManyToManyField(
                limit_choices_to={"role": "client"},
                related_name="client_sessions",
                through="gym.Booking",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="workoutsession",
            name="gym",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                to="gym.gym",
            ),
        ),
        migrations.AddField(
            model_name="workoutsession",
            name="trainer",
            field=models.ForeignKey(
                limit_choices_to={"role": "trainer"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trainer_sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to="gym.workoutsession",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="booking",
            unique_together={("user", "session")},
        ),
    ]
