# Generated by Django 5.2.5 on 2025-08-31 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gym", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="canceled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
