# Generated by Django 5.2.5 on 2025-08-31 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gym", "0003_booking_canceled_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="gym",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="workoutsession",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
